const VERSION='uxpass_v08';
const lessons=[
{id:'l1',day:1,chapter:'UX概論',title:'UXは「画面」ではなく体験全体',minutes:5,terms:['UX','UI','CX','利用前・利用中・利用後'],body:`UXは、利用者がサービスや製品と関わる前後を含めた体験全体を指す。画面の見た目や操作しやすさは重要だが、それだけでUXが良いとは限らない。たとえば操作は簡単でも、予約後の不安が強ければ体験全体の評価は下がる。UX検定では、UI改善だけに飛びつかず、利用者が何を達成したいのか、どの場面で困っているのかを考える姿勢が問われやすい。`},
{id:'l2',day:1,chapter:'UX概論',title:'UX・UI・ユーザビリティの違い',minutes:6,terms:['UI','ユーザビリティ','UX'],body:`UIは利用者が直接触れる画面や操作部品、ユーザビリティは目的達成のしやすさ、効率、満足などに関わる使いやすさである。UXはそれらを含みつつ、利用前の期待、利用中の感情、利用後の印象まで含む。試験では「操作しやすい＝UXが必ず良い」と単純化しないことが大切。`},
{id:'l3',day:2,chapter:'HCD',title:'HCDは利用者理解から始まる',minutes:6,terms:['HCD','人間中心設計','反復'],body:`HCDは、人間の特性や利用状況を理解し、その理解にもとづいて設計・評価・改善を反復する考え方である。最初から解決策を決めるのではなく、誰が、どの状況で、何に困っているのかを確認する。UX検定では、原因が分からない段階でデザイン変更に進む選択肢は慎重に見る。`},
{id:'l4',day:2,chapter:'HCD',title:'要求は「欲しい機能」だけではない',minutes:5,terms:['要求定義','利用状況','ステークホルダー'],body:`要求定義では、利用者が言った要望をそのまま機能に置き換えるだけでは不十分である。背景にある目的、制約、業務、感情、組織側の条件を整理する必要がある。利用者の発言は重要な材料だが、観察やログなど他の情報と組み合わせて判断する。`},
{id:'l5',day:3,chapter:'リサーチ',title:'調査手法は目的で選ぶ',minutes:6,terms:['インタビュー','アンケート','観察調査','ログ分析'],body:`インタビューは考えや背景を深く知るのに向き、アンケートは多数の傾向把握に向く。観察調査は本人が言語化できない行動や環境要因を見つけやすい。ログ分析は実際の行動量や離脱箇所を把握しやすい。どの手法も万能ではなく、知りたいことに合わせて選ぶ。`},
{id:'l6',day:3,chapter:'リサーチ',title:'インタビューで聞くべきこと',minutes:5,terms:['半構造化インタビュー','誘導質問','事実'],body:`インタビューでは「この機能ほしいですか」のような誘導より、直近の行動や困った場面を具体的に聞く。意見や希望だけでなく、実際に何をしたか、なぜそうしたかを確認することで、要求や課題の解像度が上がる。`},
{id:'l7',day:4,chapter:'分析',title:'ペルソナは飾りではない',minutes:5,terms:['ペルソナ','シナリオ','ターゲット'],body:`ペルソナは代表的な利用者像を具体化し、関係者間で利用者理解を揃えるために使う。単なるプロフィールではなく、目的、状況、課題、行動特性が設計判断に使える形で整理されている必要がある。シナリオは、その人物がどの状況で何を達成しようとするかを表す。`},
{id:'l8',day:4,chapter:'分析',title:'カスタマージャーニーで体験を時系列に見る',minutes:6,terms:['カスタマージャーニー','タッチポイント','感情曲線'],body:`カスタマージャーニーは、利用者が目的達成までに経験する流れを時系列で整理する。タッチポイント、行動、感情、課題を並べることで、画面単体では見えない体験上の問題を発見しやすくなる。`},
{id:'l9',day:5,chapter:'設計',title:'プロトタイプは早く試すための道具',minutes:5,terms:['プロトタイプ','ワイヤーフレーム','反復'],body:`プロトタイプは完成品ではなく、仮説を早く試すための表現である。紙、ワイヤーフレーム、クリック可能な画面など、検証したい内容に応じて忠実度を選ぶ。見た目を作り込む前に、流れや理解しやすさを確認できる。`},
{id:'l10',day:5,chapter:'評価',title:'評価は最後だけではない',minutes:5,terms:['ユーザビリティテスト','形成的評価','総括的評価'],body:`評価はリリース直前だけでなく、設計途中にも行う。形成的評価は改善点を見つけるため、総括的評価は完成度や目標達成を確認するために行う。UX検定では、評価を改善サイクルの一部として捉える。`}
];
const comparisons=[
{a:'UX',b:'UI',left:'利用前・利用中・利用後を含む体験全体。感情や期待も含む。',right:'画面、ボタン、入力欄など利用者が接する接点。'},
{a:'ペルソナ',b:'シナリオ',left:'代表的な利用者像。目的・状況・課題を持つ人物像。',right:'その人物が目的達成のために行動する流れや場面。'},
{a:'インタビュー',b:'観察調査',left:'考え・背景・理由を深く聞く。発言ベース。',right:'実際の行動・環境・無意識のつまずきを見る。'},
{a:'カスタマージャーニー',b:'サービスブループリント',left:'利用者視点で行動・感情・接点を時系列に整理。',right:'顧客接点に加え、裏側の業務や仕組みも整理。'}
];
const questions=[
{type:'case',area:'UX概論',q:'ECサイトの購入完了率が低い。担当者は「購入ボタンを目立つ色に変えよう」と提案している。UXの考え方として、最初に行う対応として最も適切なのはどれか。',choices:['利用者がどの場面で離脱しているかを調査し、原因を特定する','購入ボタンを競合サイトと同じ色にする','トップページのビジュアルだけを刷新する','購入完了率が低いのでフォーム項目をすべて削除する'],answer:0,explain:'原因が分からない段階でUI変更に飛びつくのは危険。まず利用者の行動や離脱箇所を把握し、課題を特定してから改善案を考える。',why:['ボタン色変更は改善案の一つだが、原因特定前では早い','競合模倣は利用者や文脈に合うとは限らない','見た目だけの刷新では購入率低下の原因に届かない']},
{type:'compare',area:'UX概論',q:'「操作は簡単だが、利用後に不安が残り評価が低い」というサービスについて、最も適切な説明はどれか。',choices:['ユーザビリティだけでなくUX全体に課題がある可能性がある','UIが存在しないため評価が低い','操作が簡単ならUXに課題はない','不安は設計対象ではない'],answer:0,explain:'UXは操作中だけでなく、利用後の感情や安心感も含む。操作が簡単でも体験全体の評価が低いことはある。'},
{type:'case',area:'HCD',q:'新しい予約サービスの企画会議で、社内から多くの機能要望が出た。しかし実際の利用者像や利用場面はまだ確認できていない。HCDの進め方として最も適切なのはどれか。',choices:['利用者や利用状況を調査し、要求を整理してから設計する','社内要望をすべて実装してから評価する','最も声の大きい部署の要望を優先する','競合にある機能を同じ順番で実装する'],answer:0,explain:'HCDでは利用者理解を起点にする。社内要望は重要な制約や要求の一部だが、利用者の目的や状況と照らして整理する必要がある。'},
{type:'method',area:'リサーチ',q:'利用者が「特に困っていない」と答える一方、実際には入力途中で何度も手が止まっている。次に有効な調査として最も適切なのはどれか。',choices:['実際の利用行動を観察し、つまずきの場面を確認する','満足度だけを再度アンケートで聞く','デザイナーだけで原因を推測する','利用者に新しい機能名を考えてもらう'],answer:0,explain:'本人が困りごとを言語化できない場合、観察調査が有効。発言と実行動が食い違う場面では、行動を直接見ることで課題を発見しやすい。'},
{type:'compare',area:'分析',q:'ペルソナとシナリオの関係として最も適切なのはどれか。',choices:['ペルソナは代表的な利用者像、シナリオはその利用者が目的達成する流れを表す','ペルソナは画面遷移図、シナリオは配色ルールを表す','ペルソナとシナリオはどちらも組織図を表す','シナリオを作れば利用者像は不要になる'],answer:0,explain:'ペルソナは「誰か」、シナリオは「その人がどの状況でどう行動するか」。両者は補完関係にある。'},
{type:'case',area:'分析',q:'問い合わせが多いサービスで、利用者の行動を時系列で整理したところ、申込前の比較段階で不安が高まっていることが分かった。次に検討すべき対象として最も適切なのはどれか。',choices:['申込前の情報提供や比較検討時の接点を改善する','申込後の完了画面だけを装飾する','利用者の不安はサービス範囲外として扱う','問い合わせ担当者の人数だけを増やす'],answer:0,explain:'カスタマージャーニーで申込前に課題が見えたなら、その時点の接点や情報提供を改善対象にする。'},
{type:'case',area:'設計',q:'新機能の画面案について、関係者の意見が割れている。まだ大きな開発コストはかけたくない。次に行うこととして最も適切なのはどれか。',choices:['低忠実度のプロトタイプを作り、利用者に試してもらう','すぐに本番実装して反応を見る','最も役職が高い人の案を採用する','画面の色だけを先に決める'],answer:0,explain:'プロトタイプは仮説を早く検証する道具。低コストで利用者の理解や操作の流れを確認できる。'},
{type:'case',area:'評価',q:'プロトタイプのユーザビリティテストで、参加者の多くが同じ入力欄で迷った。次に最も適切なのはどれか。',choices:['迷いの原因を分析し、ラベルや導線を修正して再評価する','参加者が慣れていないだけとして無視する','テストを中止して本番公開する','迷った参加者を集計から除外する'],answer:0,explain:'評価は改善につなげるために行う。同じ箇所で迷いが起きるなら設計上の課題として扱い、修正後に再確認する。'},
{type:'compare',area:'リサーチ',q:'多数の利用者の傾向を把握したい場合と、少数の利用者の背景を深く知りたい場合の組み合わせとして最も適切なのはどれか。',choices:['傾向把握はアンケート、背景理解はインタビュー','傾向把握はペルソナ、背景理解は配色','傾向把握はプロトタイプ、背景理解はABテストのみ','どちらも必ず観察調査だけで行う'],answer:0,explain:'アンケートは多数の傾向把握に向き、インタビューは背景や理由の深掘りに向く。目的に応じて手法を選ぶ。'},
{type:'case',area:'HCD',q:'社内では「若者向けアプリ」と考えていたが、実際の利用者には中高年も多いことがログから分かった。次に適切な対応はどれか。',choices:['想定利用者と実利用者の差を踏まえ、利用者像と要求を見直す','当初の想定を優先して中高年の利用を無視する','若者向けの色だけを強める','ログは定量情報なので設計には使わない'],answer:0,explain:'実データから想定とのずれが分かった場合、利用者理解を更新し、要求や設計方針に反映する。HCDは反復的に見直す。'},
{type:'case',area:'UX概論',q:'あるサービスは初回利用時の評価は高いが、継続利用率が低い。UXの観点で追加して確認すべきことはどれか。',choices:['利用後・再利用時の体験や価値が維持されているか','初回画面の配色だけが最新か','ロゴの印象だけが良いか','開発者が気に入っているか'],answer:0,explain:'UXは利用後や継続利用も含む。初回だけでなく、再利用したくなる価値や不満を確認する必要がある。'},
{type:'case',area:'要求定義',q:'利用者が「通知を増やしてほしい」と言った。要求定義として最も適切な対応はどれか。',choices:['なぜ通知が必要なのか、どの場面で何を知りたいのかを確認する','言われた通り通知をすべて増やす','通知音を派手にする','通知を実装せず無視する'],answer:0,explain:'発言は要求の入口。背景にある目的や状況を確認し、解決策が通知でよいのかを検討する。'}
];
function getState(){return JSON.parse(localStorage.getItem(VERSION)||'{"lesson":0,"done":[],"wrong":[],"xp":0}')}function setState(s){localStorage.setItem(VERSION,JSON.stringify(s))}function reset(){localStorage.removeItem(VERSION);location.href='index.html'}
function shuffle(arr){return arr.map(v=>[Math.random(),v]).sort((a,b)=>a[0]-b[0]).map(x=>x[1])}
function nav(active){return `<div class="nav"><div class="nav-inner">${[['index.html','ホーム','🏠'],['study.html','学習','📖'],['quiz.html','問題','✍️'],['review.html','復習','🔁'],['profile.html','記録','👤']].map(n=>`<a class="${active==n[1]?'active':''}" href="${n[0]}">${n[2]}<br>${n[1]}</a>`).join('')}</div></div>`}
function header(){let s=getState();return `<div class="top"><div class="brand">UXPASS</div><span class="pill">Day ${Math.min(14,Math.floor(s.lesson/2)+1)} / 14</span></div>`}
function toast(t){let el=document.createElement('div');el.className='toast';el.textContent=t;document.body.appendChild(el);setTimeout(()=>el.classList.add('show'),10);setTimeout(()=>el.remove(),1800)}
function renderHome(){let s=getState(), l=lessons[Math.min(s.lesson,lessons.length-1)], pct=Math.round((s.done.length/lessons.length)*100);document.body.innerHTML=`<main class="app">${header()}<section class="hero"><div class="small">試験まで2週間モード</div><h1>今日はここから。</h1><p class="sub">${l.chapter}：${l.title}<br>約${l.minutes+8}分。読んで、考えて、数問だけ解く。</p><div class="meter"><div class="bar" style="width:${pct}%"></div></div><button class="btn" onclick="location.href='study.html'">▶ はじめる</button></section><section class="grid"><a class="mini" href="quiz.html"><b>${questions.length}</b><span class="small">本番寄せ問題</span></a><a class="mini" href="review.html"><b>${s.wrong.length}</b><span class="small">復習待ち</span></a><a class="mini" href="search.html"><b>${comparisons.length}</b><span class="small">比較カード</span></a><a class="mini" href="profile.html"><b>${s.xp}</b><span class="small">XP</span></a></section><div class="section-title">今回の方針</div><section class="card"><p class="content">用語暗記ではなく、実際の場面で「次に何をするべきか」を考える問題を中心にしています。</p></section><button class="btn ghost" onclick="reset()">進捗を初期化</button></main>${nav('ホーム')}`}
function renderStudy(){let s=getState(),idx=Math.min(s.lesson,lessons.length-1),l=lessons[idx];document.body.innerHTML=`<main class="app">${header()}<section class="card"><div class="small">${l.chapter} / ${idx+1} of ${lessons.length}</div><h1 class="lesson-title">${l.title}</h1><div class="meter"><div class="bar" style="width:${((idx)/lessons.length)*100}%"></div></div><p class="content">${highlight(l.body,l.terms)}</p><div>${l.terms.map(t=>`<span class="tag">${t}</span>`).join('')}</div></section><section class="card"><div class="section-title" style="margin-top:0">考えてみる</div><p class="content">この考え方を本番では、用語の定義ではなく「ある状況で最も適切なのはどれか」として問われることが多いです。</p><button class="btn secondary" onclick="location.href='quiz.html?lesson=${idx}'">この範囲の問題へ</button></section><button class="btn" onclick="completeLesson()">読了して次へ</button></main>${nav('学習')}`}
function highlight(text,terms){terms.forEach(t=>text=text.replaceAll(t,`<span class="term" onclick="toast('${t}：関連用語カードは検索で確認できます')">${t}</span>`));return text}
function completeLesson(){let s=getState();if(!s.done.includes(s.lesson))s.done.push(s.lesson);s.lesson=Math.min(s.lesson+1,lessons.length-1);s.xp+=10;setState(s);location.href='study.html'}
function renderQuiz(){let params=new URLSearchParams(location.search), lesson=params.get('lesson');let pool=questions;if(lesson!==null){let l=lessons[Number(lesson)];pool=questions.filter(q=>q.area===l.chapter||l.terms.some(t=>q.q.includes(t)||q.explain.includes(t)));if(pool.length<3)pool=questions}let qi=Number(sessionStorage.getItem('qidx')||0)%pool.length;let q=pool[qi];let order=shuffle(q.choices.map((c,i)=>({c,i})));window.currentQ=q;document.body.innerHTML=`<main class="app">${header()}<section class="card"><div class="small">${q.type} / ${q.area}</div><h1 class="lesson-title">Q${qi+1}</h1><p class="content">${q.q}</p><div id="opts">${order.map(o=>`<button class="quiz-option" onclick="answer(${o.i},this)">${o.c}</button>`).join('')}</div><div id="result"></div></section><button class="btn secondary" onclick="nextQ()">次の問題</button></main>${nav('問題')}`}
function answer(i,btn){let q=window.currentQ;document.querySelectorAll('.quiz-option').forEach(b=>b.disabled=true);if(i===q.answer){btn.classList.add('correct');document.getElementById('result').innerHTML=`<div class="explain"><b>正解。</b><br>${q.explain}${q.why?'<br><br><b>他の選択肢が弱い理由</b><br>'+q.why.map(w=>'・'+w).join('<br>'):''}</div>`;let s=getState();s.xp+=5;setState(s)}else{btn.classList.add('wrong');let s=getState();s.wrong.push(q.q);setState(s);document.getElementById('result').innerHTML=`<div class="explain"><b>惜しい。</b><br>${q.explain}</div>`}}
function nextQ(){sessionStorage.setItem('qidx',Number(sessionStorage.getItem('qidx')||0)+1);location.href='quiz.html'}
function renderReview(){let s=getState();document.body.innerHTML=`<main class="app">${header()}<section class="hero"><h1>復習</h1><p class="sub">間違えた問題を、明日・3日後・7日後に戻す想定で育てていく予定。</p></section><section class="list">${s.wrong.slice(-8).reverse().map(w=>`<div class="row"><span>${w}</span></div>`).join('')||'<div class="card">まだ復習対象はありません。</div>'}</section></main>${nav('復習')}`}
function renderSearch(){document.body.innerHTML=`<main class="app">${header()}<section class="hero"><h1>比較カード</h1><p class="sub">UX検定で混同しやすい概念を左右で整理。</p></section>${comparisons.map(c=>`<section class="card"><div class="compare"><div class="box"><b>${c.a}</b><p>${c.left}</p></div><div class="box"><b>${c.b}</b><p>${c.right}</p></div></div></section>`).join('')}</main>${nav('探す')}`}
function renderProfile(){let s=getState();document.body.innerHTML=`<main class="app">${header()}<section class="hero"><h1>記録</h1><p class="sub">完了 ${s.done.length} レッスン / XP ${s.xp}</p><div class="meter"><div class="bar" style="width:${Math.round(s.done.length/lessons.length*100)}%"></div></div></section><section class="card"><b>次に改善すること</b><p class="content">Chapter2以降もこの「ケース中心・比較中心」の品質で増やしていきます。</p></section><button class="btn ghost" onclick="reset()">進捗を初期化</button></main>${nav('記録')}`}
function renderMock(){document.body.innerHTML=`<main class="app">${header()}<section class="hero"><h1>模試</h1><p class="sub">v0.8では準備中。まずは本番レベルの短問を固めています。</p><button class="btn" onclick="location.href='quiz.html'">問題演習へ</button></section></main>${nav('模試')}`}
